-- MySQL Script generated by MySQL Workbench
-- Thu May  4 16:48:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `default_schema` ;
USE `default_schema` ;

-- -----------------------------------------------------
-- Table `default_schema`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`customer` (
  `customerID` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `phone` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `birthdate` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`customerID`),
  UNIQUE INDEX `customerID_UNIQUE` (`customerID` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `default_schema`.`cancellation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`cancellation` (
  `cancellationID` INT NOT NULL,
  `cancellation_date` DATE NULL DEFAULT NULL,
  `customerID` INT NULL DEFAULT NULL,
  `reason` VARCHAR(45) NULL DEFAULT NULL,
  `customerID` INT NOT NULL,
  PRIMARY KEY (`cancellationID`),
  INDEX `fk_cancellation_customer1_idx` (`customerID` ASC) VISIBLE,
  CONSTRAINT `fk_cancellation_customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `default_schema`.`customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `default_schema`.`customer_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`customer_plan` (
  `customerID` INT NOT NULL,
  `customer_planID` INT NOT NULL,
  `cancellationID` INT NOT NULL,
  INDEX `fk_customer_plan_customer_idx` (`customerID` ASC) VISIBLE,
  PRIMARY KEY (`customer_planID`),
  INDEX `fk_customer_plan_cancellation1_idx` (`cancellationID` ASC) VISIBLE,
  CONSTRAINT `fk_customer_plan_customer`
    FOREIGN KEY (`customerID`)
    REFERENCES `default_schema`.`customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_plan_cancellation1`
    FOREIGN KEY (`cancellationID`)
    REFERENCES `default_schema`.`cancellation` (`cancellationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`call_traffic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`call_traffic` (
  `callID` INT NOT NULL,
  `calldate` DATETIME NULL DEFAULT NULL,
  `customerID` INT NOT NULL,
  `duration_minutes` INT NULL DEFAULT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `cost` DECIMAL(9,2) NULL DEFAULT NULL,
  `customer_planID` INT NOT NULL,
  PRIMARY KEY (`callID`, `customerID`),
  INDEX `fk_call_traffic_customer_plan1_idx` (`customer_planID` ASC) VISIBLE,
  CONSTRAINT `fk_call_traffic_customer_plan1`
    FOREIGN KEY (`customer_planID`)
    REFERENCES `default_schema`.`customer_plan` (`customer_planID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `default_schema`.`customer_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`customer_plan` (
  `customerID` INT NOT NULL,
  `customer_planID` INT NOT NULL,
  `cancellationID` INT NOT NULL,
  INDEX `fk_customer_plan_customer_idx` (`customerID` ASC) VISIBLE,
  PRIMARY KEY (`customer_planID`),
  INDEX `fk_customer_plan_cancellation1_idx` (`cancellationID` ASC) VISIBLE,
  CONSTRAINT `fk_customer_plan_customer`
    FOREIGN KEY (`customerID`)
    REFERENCES `default_schema`.`customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_customer_plan_cancellation1`
    FOREIGN KEY (`cancellationID`)
    REFERENCES `default_schema`.`cancellation` (`cancellationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `default_schema`.`plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`plan` (
  `planID` INT NOT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `duration` VARCHAR(45) NULL DEFAULT NULL,
  `cost` DECIMAL(9,2) NULL DEFAULT NULL,
  `features` VARCHAR(45) NULL DEFAULT NULL,
  `customer_planID` INT NOT NULL,
  PRIMARY KEY (`planID`),
  INDEX `fk_plan_customer_plan1_idx` (`customer_planID` ASC) VISIBLE,
  CONSTRAINT `fk_plan_customer_plan1`
    FOREIGN KEY (`customer_planID`)
    REFERENCES `default_schema`.`customer_plan` (`customer_planID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `default_schema`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `default_schema`.`transaction` (
  `transactionID` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  `amount` DECIMAL(9,2) NULL DEFAULT NULL,
  `planID` INT NOT NULL,
  `customerID` INT NOT NULL,
  `customer_planID` INT NOT NULL,
  PRIMARY KEY (`transactionID`, `planID`),
  UNIQUE INDEX `transactionID_UNIQUE` (`transactionID` ASC) VISIBLE,
  INDEX `fk_transaction_customer1_idx` (`customerID` ASC) VISIBLE,
  INDEX `fk_transaction_customer_plan1_idx` (`customer_planID` ASC) VISIBLE,
  CONSTRAINT `fk_transaction_customer1`
    FOREIGN KEY (`customerID`)
    REFERENCES `default_schema`.`customer` (`customerID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transaction_customer_plan1`
    FOREIGN KEY (`customer_planID`)
    REFERENCES `default_schema`.`customer_plan` (`customer_planID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
